algo: ppo
env_id: LunarLander-v3
use_cnn: false
seed: 42
device: cuda
total_steps: 1500000
learning_starts: 0
rollout_length: 2048
train_freq: 2048
gradient_steps: 1
max_ep_len: 1000
eval_interval: 20000
eval_episodes: 10
publish_to_hub: true
hf_repo_id: "ZiadHF/ppo-lunarlander-v3"

agent_params:
  lr: 0.0003
  gamma: 0.99
  clip_ratio: 0.2
  lam: 0.95
  train_pi_iters: 20
  train_v_iters: 20
  target_kl: 0.015
  ent_coef: 0.01
  batch_size: 64
  hidden_dims: [256, 256]
  max_ep_len: 1000
