algo: sac_cnn
env_id: CarRacing-v3
use_cnn: true
feature_dim: 512
seed: 42
device: cuda
total_steps: 2000000
learning_starts: 20000
train_freq: 1
gradient_steps: 1
max_ep_len: 1000
eval_interval: 25000
eval_episodes: 5
publish_to_hub: true
hf_repo_id: "ZiadHF/sac-carracing-cnn_2"

agent_params:
  lr: 0.0001
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  automatic_entropy_tuning: true
  buffer_size: 100000
  batch_size: 512
  hidden_dims: [256, 256]
