algo: sac
env_id: LunarLander-v3
use_cnn: false
seed: 42
device: cuda
total_steps: 1000000
learning_starts: 10000
train_freq: 1
gradient_steps: 1
max_ep_len: 1000
eval_interval: 10000
eval_episodes: 10
publish_to_hub: true
hf_repo_id: "ZiadHF/sac-lunarlander-v3"

agent_params:
  lr: 0.0003
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  automatic_entropy_tuning: true
  buffer_size: 1000000
  batch_size: 256
  hidden_dims: [400, 300]
