algo: td3
env_id: LunarLander-v3
use_cnn: false
seed: 42
device: cuda
total_steps: 300000
learning_starts: 25000
train_freq: 1
gradient_steps: 1
max_ep_len: 1000
eval_interval: 10000
eval_episodes: 10
publish_to_hub: true
hf_repo_id: "ZiadHF/td3-lunarlander-v3"

agent_params:
  lr: 0.0003
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_delay: 2
  buffer_size: 1000000
  batch_size: 256
  hidden_dims: [400, 300]
  exploration_noise: 0.1
